# Define variables
LOGS_DIR=/fast/najroldi/logs/algoperf
EXE=/lustre/home/najroldi/algorithmic-efficiency/script/tune/single_workload/run.sh

# Args
workload=criteo1tb
submission=reference_algorithms/muon_def/pytorch/muon_kj_overlapped_reduce_scatter.py
search_space=script/tune/search_spaces/sweep_01.json
num_tuning_trials=96
study=1
rng_seed=1
name=sweep_01
eval_every_n_steps=False
allow_tf32=True
torch_compile=True

# Logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Specs
request_memory = 250000
request_cpus = 16
request_gpus = 4
requirements = TARGET.CUDACapability == 8.0
# requirements = (TARGET.CUDACapability >= 8.0) && (TARGET.CUDADeviceName != "NVIDIA B200")

# requirements = TARGET.CUDACapability >= 8.0
# requirements =  (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
# max_materialize = 8

# Arguments to the script.
executable = $(EXE)
arguments = \
  $(Process) \
  $(workload) \
  $(submission) \
  $(search_space) \
  $(num_tuning_trials) \
  $(study) \
  $(name) \
  $(eval_every_n_steps) \
  $(rng_seed) \
  $(allow_tf32) \
  $(torch_compile) \
  $(request_gpus)

queue $(num_tuning_trials)
