# Define variables
LOGS_DIR=/fast/najroldi/logs/algoperf
EXE=/home/najroldi/algorithmic-efficiency/script/pytorch/v100_test/auto_run_array.sh

num_jobs=1

# Job specific vars
# workload_or_id=$(Process)
workload_or_id=imagenet_resnet
framework=pytorch
submission=prize_qualification_baselines/external_tuning/pytorch_nadamw_full_budget.py
search_space=prize_qualification_baselines/external_tuning/tuning_search_space.json
name=v100_test_05
study=1
num_tuning_trials=1
rng_seed=96
eval_workers=2
omp_threads=2

# Args
executable = $(EXE)
arguments = \
  $(workload_or_id) \
  $(framework) \
  $(submission) \
  $(search_space) \
  $(name) \
  $(study) \
  $(num_tuning_trials) \
  $(rng_seed) \
  $(eval_workers) \
  $(omp_threads)

# Logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Specs
request_memory = 700000
request_cpus = 36
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "Tesla V100-SXM2-32GB")

queue $(num_jobs)